### ISSUE TITLE
Angular 5 road map

### ISSUE THREAD

**Issue by robertmazzo** [hash-bang/angular-d3-hierarchy#2]
Hello,
Your d3-hierarchy looks great, and I was wondering if you plan to release an Angular 5.x version of that.
I'm looking for something that would represent data centers and location in a hierarchy "spider web" format - exactly the way you've developed yours. 
In addition, each node would provide some configuration per site (i.e. a modal popup, etc.).

We have an old Silverlight web application which uses the old Telerik SpiderWeb control for Silverlight, but that's obsolete.
Any suggestions and/or guidance appreciated, as I am doing extensive research on the topic.
best,
Bob

**Comment by hash-bang** [comment]
Sorry @robertmazzo, while we're still using AngularJS with a few sites we've largely migrated over to VueJS for the new stuff.

So there are no plans to upgrade I'm afraid. If you do get it converted over do let me know and I'll link to it.
